In [1]:
import glob as g
import numpy as np
import random as r
from sklearn import svm

In [2]:
file_path='C:\\Users\\SEO\\Desktop\\Makenaide\\Data and Models\\DS3_NG OK Oridata\\'

train_data=np.loadtxt(file_path+'17276_OK_data.csv', delimiter=',', dtype=np.float32)
train_data=np.array(r.sample(train_data.tolist(), 14474))
test_data=np.loadtxt(file_path+'5604_Oridata_1.csv', delimiter=',', dtype=np.float32)

print(train_data.shape)
print(train_data)
print(test_data.shape)
print(test_data)

np.random.shuffle(test_data)
answers=test_data[:, 22500] ; test_data=test_data[:, 0:22500]
train_data=train_data[:, 0:22500]

(14474, 22503)
[[ 21.  20.  21. ...   1.   1.   0.]
 [107. 109. 108. ...   1.   1.   6.]
 [  3.   3.   3. ...   1.   1.   7.]
 ...
 [  6.   5.   7. ...   1.   1.   7.]
 [  0.   0.   0. ...   1.   1.   1.]
 [104. 104. 102. ...   1.   1.   6.]]
(5604, 22503)
[[26. 23. 26. ...  0.  1.  0.]
 [18. 22. 25. ...  0.  1.  0.]
 [20. 26. 24. ...  0.  1.  0.]
 ...
 [ 0.  0.  0. ...  1.  1.  8.]
 [ 3.  1.  5. ...  1.  1.  8.]
 [ 0.  0.  0. ...  1.  1.  8.]]


In [7]:
obj_ocs=svm.OneClassSVM(gamma=0.001, kernel='rbf', nu=0.08)

obj_ocs.fit(train_data)

ocs_preds=obj_ocs.predict(test_data)

In [8]:
num_NG=answers.tolist().count(0) ; num_OK=answers.tolist().count(1)
num_correct_NG=0 ; num_correct_OK=0
 
for o, a in zip(ocs_preds, answers) :
    if o==-1 and a==0 :
        num_correct_NG += 1
    elif o==1 and a==1 :
        num_correct_OK += 1

print('NG data Accuracy : %.2f' % (num_correct_NG/num_NG*100))
print('OK data Accuracy : %.2f' % (num_correct_OK/num_OK*100))

NG data Accuracy : 100.00
OK data Accuracy : 76.09
